name: analysis
on: [ push, pull_request ]

env:
  ORG_GRADLE_PROJECT_checksumFailOn: never
  ORG_GRADLE_PROJECT_checksumIgnore: false
  ORG_GRADLE_PROJECT_checksumPrint: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
    env:
      JAVA_VERSION: ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Run analyzers
        run: ./.github/scripts/analyze.sh
