name: lincheck
on: [ push, pull_request ]

env:
  ORG_GRADLE_PROJECT_checksumFailOn: never
  ORG_GRADLE_PROJECT_checksumIgnore: false
  ORG_GRADLE_PROJECT_checksumPrint: true
  JAVA_VERSION: 17

jobs:
  lincheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3.4.1
        with:
          cache: 'gradle'
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Run lincheck
        run: |
          set -eux
          ./gradlew lincheckTest
